export enum CURRENCY_ACTION_TYPES {
  SWAP = '@@CURRENCY/SWAP',
  CHANGE_AMOUNT = '@@CURRENCY/CHANGE_AMOUNT',
  CHANGE_BASE = '@@CURRENCY/CHANGE_BASE',
  CHANGE_QUOTE = '@@CURRENCY/CHANGE_QUOTE',
  GET_CONVERSIONS_REQUEST = '@@CURRENCY/GET_CONVERSIONS_REQUEST',
  GET_CONVERSIONS_FULFILLED = '@@CURRENCY/GET_CONVERSIONS_FULFILLED',
  GET_CONVERSIONS_REJECTED = '@@CURRENCY/GET_CONVERSIONS_REJECTED',
}
